version: '2'
services:
  nginx:
      build:
        context: .
        dockerfile: ./.docker-config/nginx/Dockerfile
      ports:
          - 80:80
      volumes:
          - ./src/web:/var/www/html/web

  php:
      build:
        context: .
        dockerfile: ./.docker-config/php/Dockerfile
      expose:
          - 9000
      volumes:
          - ./src/config:/var/www/html/config
          - ./src/templates:/var/www/html/templates
          - ./src/modules:/var/www/html/modules
          - ./src/web:/var/www/html/web
          - ./src/composer.json:/var/www/html/composer.json
      environment:
        ENVIRONMENT: dev
        LANG: C.UTF-8
        DB_DRIVER: pgsql
        DB_SERVER: database
        DB_USER: craft
        DB_PASSWORD: project
        DB_DATABASE: craft
        PGPASSWORD: secret
        DB_SCHEMA: public
        DB_PORT: '5432'
        DB_TABLE_PREFIX: ""
        SITE_URL: http://localhost
        SECURITY_KEY: asdfasdfasdfasdfasdf

  database:
      image: postgres:10.6
      volumes:
          - postgresql-data:/var/lib/postgresql/data
      ports:
          - 3306:5432
      environment:
          POSTGRES_USER: craft
          POSTGRES_PASSWORD: project
          POSTGRES_DB: craft
          POSTGRES_INITDB_ARGS: "-E UTF8"

  phpmyadmin:
      image: phpmyadmin/phpmyadmin
      ports:
          - 8085:80
      environment:
          PMA_HOST: database

volumes:
  postgresql-data:
